### ISSUE TITLE
Create a project card for YouthJusticeNav

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/YouthJusticeNav#1]
### Overview
Provide collateral for the HackforLA website

### Action Items
- [x]   Gather items
  - [x]  600 x 400 image #3 
     - [x]  Alt image text
  - [x] 1500 x 700 hero image (please do not put project title on hero image) #3 
     - [x]  Alt image text
  - [x]  Name of project
  - [x]  A blurb about your project
  - [x]  Links (github, slack channel url, Testing Site, Live Site, etc.)
  - [x]  Any resources for a Getting Started link (a link to a wiki, readme(s) or both)
  - [x]  What you are looking for skills wise
  - [x]  Partner(s)
  - [x]  Location
  - [x] Leadership
     - [x] Name
     - [x] Role
     - [x] GitHub handle
     - [x] Slack Handle
  - [x]  Status
- [x]   Add project Card to website

### Resources/Instructions
See project cards on the hackforla.org website for examples

**Comment by ltung05** [comment]
Name: Youth Justice Nav
Links:
- GitHub: https://github.com/hackforla/YouthJusticeNav/
- Slack: https://hackforla.slack.com/archives/C01J94D6GAC
- Readme: https://github.com/hackforla/YouthJusticeNav/blob/main/README.md
Looking for:
- Category: Content
  Skills: Content Writer
- Category: UI/UX
  Skills: UI Designer
- Category: UI/UX
  Skills: UX Researcher
technologies:
- Google Docs
- Google Sheets
- Figma
- Miro
Partner: UCLA Law School, Code for America
Leadership:
- name: Leroy Tung
- Role: Product Manager
- GitHub handle: ltung05
- Slack Handle: U01G75XUYHX
- Name: Nielsen
- Role: Product Manager
- GitHub Handle: nielsen
- Slack Handle: U01G0PX0NJY
- Name: Daniel Lee
- Role: Product Designer
- GitHub handle: Daniel Lee
vertical: Justice
sdg: 
status: active

leadership:
  - name: Bonnie Wolfe
    role: Agile Coach
    links:
      slack: 'https://hackforla.slack.com/team/UE1UG1YFP'
      github: 'https://github.com/ExperimentsInHonesty'
    picture: https://avatars.githubusercontent.com/ExperimentsInHonesty

**Comment by nielseny** [comment]
![Youth Justice Nav Logo 600 x 400](https://user-images.githubusercontent.com/75336198/103841948-8c343b00-5049-11eb-8cca-81317514489e.png)
 Logo created by Daniel

**Comment by ExperimentsInHonesty** [comment]
@nielseny I went ahead and grabbed the description from the readme and edited it down a little bit.  I am going to send this off to the website team.

**Comment by dmcneary** [comment]
Hi all,

I posted screenshots of this project on the website, let me know if anything looks off:
https://github.com/hackforla/website/issues/922#issuecomment-757403941

**Comment by ExperimentsInHonesty** [comment]
@dmcneary the card and page look perfect.  Consider this the signoff!
