### ISSUE TITLE
Notes on the Project

### ISSUE THREAD

**Issue by j100892** [hackforla/YouthJusticeNav#11]
https://docs.google.com/document/d/1zvfayjp240pvMgl4j9150L52UCVsxRKMdtNKa2WW9Gg/edit#heading=h.gjdgxs

**Comment by nielseny** [comment]
Hi @j100892, I tried to open it but it says I have no access, do you mind adding this link to the Google Drive so we can access it? Thank you!

**Comment by Olivia-Chiong** [comment]
@j100892 Hi, I just tried to open this file and also found I did not have access. Are you able to move the document to this [drive](https://drive.google.com/drive/folders/1-DkXZx0u5ZiCMH2K9eVNHPC5kVDSdu7H?usp=sharing)please?

**Comment by j100892** [comment]
> @j100892 Hi, I just tried to open this file and also found I did not have access. Are you able to move the document to this [drive](https://drive.google.com/drive/folders/1-DkXZx0u5ZiCMH2K9eVNHPC5kVDSdu7H?usp=sharing) please?

Hey! The file in question is the same one as is is this current file in the drive: https://drive.google.com/file/d/1WM0JxKFqTUga-7oC65lMTHNvVpt4sMMD/view?usp=sharing

**Comment by ltung05** [comment]
Leroy to update wiki
