### ISSUE TITLE
Create YJN: How to Write a Research Plan

### ISSUE THREAD

**Issue by ltung05** [hackforla/YouthJusticeNav#118]
### Overview
Create a document to provide instructions on how to write a research plan similar to the TWE document.

### Action Items
- [x] Delete this document [YJN: How to Write a Research Plan](https://docs.google.com/document/d/1JyrzIaJZ9_ZpoAOFkTS_IGjCBQufcBDUZx84gAfnOlo/edit#)
- [x] make a copy of the YJN Report template
- [x] Copy the contents from "TWE: How to Write a Research Plan" into it
- [x] Utilize research plans created by Taylor and Meghan, update screenshots within the document, so they are relevant
- [x] Replace links for all research issues

### Resources/Instructions
- Sample [TWE: How to Write a Research Plan](https://docs.google.com/document/d/1Cwc0w4ZPUI8989w3jU8BW2LzLK_Tl5gHdI0VxN5ej0o/edit)
- [Folder](https://drive.google.com/drive/folders/10fob6XVUw-BtNjlUN-mMGsRqBvUIbYp3) where the document you will create goes
- [YJN Report Template](https://docs.google.com/document/d/1rDmXOXfpfXqJ0O7i5bqLRi5IrADp1Fal6z-x4ysUCbs/template/preview)

#### Issue assets
- [YJN: How to Write a Research Plan](https://docs.google.com/document/d/1TqFFTOQuCauNQicvMSAZr-JtD_5CgeCeIeXl_O8Ocpo/edit?usp=sharing)

**Comment by ltung05** [comment]
Done.

https://docs.google.com/document/d/1TqFFTOQuCauNQicvMSAZr-JtD_5CgeCeIeXl_O8Ocpo/edit?usp=sharing

**Comment by Rabia2219** [comment]
@ltung05 
Hi Leroy,
Can you please link the document in the main body under:

Issue assets
- [YJN: How to Write a Research Plan]

Great job on the document. Some feedback:
- The title of the document has the wrong font.
- In the Instructions section, the General Principles subsection is missing from our document. 
- In the Research Methods section, the screenshots for 'how to change heading levels' are missing in our document.

**Comment by Rabia2219** [comment]
check Folder link in resources

**Comment by ltung05** [comment]
> @ltung05 Hi Leroy, Can you please link the document in the main body under:
> 
> Issue assets
> 
> * [YJN: How to Write a Research Plan] **- done**
> 
> Great job on the document. Some feedback:
> 
> * The title of the document has the wrong font. **- don't have edit access to TWE document, is there a default font we use?**
> * In the Instructions section, the General Principles subsection is missing from our document. **- done**
> * In the Research Methods section, the screenshots for 'how to change heading levels' are missing in our document. **-done**

**Comment by ExperimentsInHonesty** [comment]
We updated the font to Oswald

**Comment by ExperimentsInHonesty** [comment]
Add new section to this wiki page
https://github.com/hackforla/YouthJusticeNav/wiki/UX-Research-Guides-and-Templates
 for YJN guides and add the new resource

**Comment by ltung05** [comment]
Link has been updated in Wiki, under UX Research Guides and Templates
