### ISSUE TITLE
Draft: YJN: Consent Form Template 

### ISSUE THREAD

**Issue by doctorsandy** [hackforla/YouthJusticeNav#125]
### Overview
We need to generate and collect consent forms so that we can move onto conducting focus groups, interviews, and participant observation.

#### Product
- [ ] Review the progress on a default form for internship and setup criteria for how to build on and customize before rebuilding whole process on this project
  - [ ] Add appropriate links and wording to this issue to make it clear what to do.
  - [ ] confirm file structure exists in the internship-ux  my drive to store the results of form once made

#### Research
- [ ] update the form with the default language from the internship project
- [ ] move form to the research google drive
- [ ] Create an issue to be able to use the template for any issues that needs a form (this will include explaining how to customize)

### Resources/Instructions
- [YJN form template](https://docs.google.com/forms/d/19ZPDEk9sIBLufJ04DaaHsIBy7oui3_-nqXeIR2fy6C8/edit)
- [Sample internship consent form](https://docs.google.com/forms/d/e/1FAIpQLSe448BM3v-Q8DUPFX109oJVwWtV9q3UzMP_wSCQmPWesbbSdQ/viewform)
- [YJN Consent Forms Template]
- [Main research folder on YJN shared drive](https://drive.google.com/drive/folders/1BU4S1kASBX8PXr5nuTXANGS_1AtK_sdX)
-

**Comment by ExperimentsInHonesty** [comment]
Duplicate issue
