### ISSUE TITLE
DNS Setup for YouthJusticeNav

### ISSUE THREAD

**Issue by nielseny** [hackforla/YouthJusticeNav#13]
### Overview
Figure out how to point the DNS at GitHub url.

### Action Items

- [ ]  Point YouthJusticeNav.org at the github account
- [ ] Point YouthJusticeNav.com and ,net at the YouthJusticeNav.org

### Resources/Instructions
https://dev.to/trentyang/how-to-setup-google-domain-for-github-pages-1p58

**Comment by ExperimentsInHonesty** [comment]
done.  The dns now points at the repository youthjusticenav.org shows the readme
