### ISSUE TITLE
Update the One-Pager for YouthJusticeNav

### ISSUE THREAD

**Issue by nielseny** [hackforla/YouthJusticeNav#17]
### Overview

Write a one-sheet for YJN project including milestones for the next 6 months.

### Action Items

- [x] Review other projects' one-sheet
- [x] Review Civic Opportunity Project one-sheet
- [x] Produce First draft of YouthJusticeNav project's one-sheet
- [x] Add partners' logos to the draft
- [ ] Review with Bonnie 

### Resources/Instructions
[Other projects' one-sheet](https://github.com/hackforla/product-managment/issues/3)
[Civic Opp Project one-sheet](https://github.com/hackforla/civic-opportunity/blob/master/Civic_Opportunity_Project_OnePage.pdf)

**Comment by nielseny** [comment]
Working document: https://docs.google.com/document/d/1NKcYSoGW2SNUrf-_osyBS9HKK7oUH7c8oQIgb5o8n2U/edit

**Comment by ExperimentsInHonesty** [comment]
@nielseny the logo that you put in the one sheet is not the right logo. That is for the entire university. The partner is the law school. Here is the correct logo 
![ggu-schooloflaw-logo](https://user-images.githubusercontent.com/37763229/105621015-ee19d200-5db7-11eb-9a9c-acd09d51a6ae.jpg). please change it.

**Comment by ExperimentsInHonesty** [comment]
We should put a link to our partners in our one sheet.

Here is the Golden Gate University School of Law
https://law.ggu.edu/

**Comment by nielseny** [comment]
Thanks Bonnie, I've changed the ggu logo and add links to our partners.

**Comment by nielseny** [comment]
Done
