### ISSUE TITLE
Setup Twitter for YouthJusticeNav

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/YouthJusticeNav#2]
### Overview
We need to lock down the Twitter account for YouthJusticeNav so that we don't loose it.

### Action Items
- [x] Setup Twitter account 
- [x] Add Twitter password to 1password
- [x] Add link to twitter account on project board

### Resources/Instructions
[Location to paste links on board ](https://github.com/hackforla/YouthJusticeNav/projects/1#card-51795877)

**Comment by nielseny** [comment]
Twitter account link added to project board.
