### ISSUE TITLE
Role Recruitment

### ISSUE THREAD

**Issue by ltung05** [hackforla/YouthJusticeNav#24]
### Overview
We need to recruit contributors for this project on an ongoing basis.

### Note
The last comment on this sheet will have our current recruiting needs listed.

### Action Items
- [x] Check the last comment on the recruiting sheet and update as necessary
- [x] If updates made, update spreadsheet

### Resources/Instructions
- [Hack for LA Recruiting Current Needs](https://docs.google.com/spreadsheets/d/1xnrwTL4kCFhecLQmXwFWVPyWjgc3DC6aQYWq8ZF_QDI/edit#gid=0)
- [UI/UX Slack Channels](https://www.designerslack.community/)
- [UI/UX Slack Channels 2](https://uxdesign.cc/the-best-slack-groups-for-ux-designers-25c621673d9c?gi=6224907f9787)
- Canva link
- Logo on Figma

**Comment by nielseny** [comment]
We've updated the notice (https://github.com/hackforla/UI-UX/projects/2#card-52993612)

**Comment by nielseny** [comment]
UX Research onboarding on Friday Feb 12th, hopefully we'll find someone!

**Comment by ltung05** [comment]
We found Erica and Dana!
