### ISSUE TITLE
Update ReadMe

### ISSUE THREAD

**Issue by ltung05** [hackforla/YouthJusticeNav#25]
### Overview
We need up-to-date ReadMe to communicate effectively with new users, contributors, and visitors on a continuous basis.

### Action Items
- [ ] Once that happens, update the link in ReadME to the template
- [ ] New person to review ReadMe identifying unanswered questions that could be addressed
  - [ ] Post suggestions in the comments below

### Resources/Instructions
- [Website ReadMe](https://github.com/hackforla/YouthJusticeNav)

**Comment by nielseny** [comment]
Add link to the one-sheet and name of the partners

**Comment by ExperimentsInHonesty** [comment]
Looks good.
