### ISSUE TITLE
Work on the budget for YouthJusticeNav's Project

### ISSUE THREAD

**Issue by nielseny** [hackforla/YouthJusticeNav#28]
### Overview
Bonnie will have a conversation with Veronica about the budget for this project

### Action Items
- [x] Bonnie to work with Olivia on budget 

### Resources/Instructions
[Project Proposal](https://docs.google.com/document/d/1OsNZzwumWmzJidN8ER-JrOV8-UcJBhjhob1HkSNp7Jg/edit?usp=sharing)

**Comment by nielseny** [comment]
Updated the document, will send it to Jyoti & Alicia for review and feedback

**Comment by Olivia-Chiong** [comment]
Budget has been approved by UCLA and we will be doing 1099 and payment through Liberty Hill.

@ExperimentsInHonesty will connect with them through Alicia's introduction.
