### ISSUE TITLE
Prepare a list of questions for Friday meeting with UCLA School of Law

### ISSUE THREAD

**Issue by ltung05** [hackforla/YouthJusticeNav#32]
### Overview
Create a google document with a list of questions for the Friday meeting.

### Action Items
- [x] Create google doc
- [x] Validate Stakeholders
- [x] Have it ready by late Thursday or early Friday for Bonnie to review

### Resources/Instructions
[Customer Discovery Step-by-Step Template](https://drive.google.com/file/d/1oMqZem4pePT14tNs48yyBhaqH3S6guEN/view)
[Customer Discovery for YJN](https://docs.google.com/document/d/1iBtrtdFR__dUFnIKPoeYtocucleGRf3kz8bBRDvOJAQ/edit)
[UCLA School of Law - Meeting Questions for 1/22/2021](https://docs.google.com/document/d/1pN4LLh8lMaUfoDlMD_Z5cVxYrsnT3piVmtvV4Xei0NU/edit)

**Comment by nielseny** [comment]
Spoke to Dean, the name of the committe is Measure J Re-Imagine LA Advisory Committee. 
The judge is retired and is now the Executive Director of the Alternatives to Incarceration Initiative for LA County.
