### ISSUE TITLE
Read the resources that were shared by Alicia & Jyoti

### ISSUE THREAD

**Issue by nielseny** [hackforla/YouthJusticeNav#35]
### Overview
We should read the resources that Alicia&Jyoti shared (context of the project and what they have done so far)

### Action Items

- [x] Read through all the documents
- [x] Make suggestions on how to utilize the information

### Resources/Instructions
[Link to the folder](https://drive.google.com/drive/u/0/folders/1wjikITXIII_UNUdWsWtQCnEZYu10SVzf)

**Comment by ltung05** [comment]
[1 - Knowledge is Power Concept Paper](https://drive.google.com/file/d/11b-PbLEH1xvHhq1Po5xR6QMSQ_-a7jS1/view?usp=sharing)
[2 - Knowledge is Power Content Map](https://drive.google.com/file/d/18NCdT5xydvfGA5VC8zn6AwcjYPOqdysQ/view?usp=sharing)
[3 - Initial Results of Youth Survey](https://drive.google.com/file/d/1MyChpQonjgK2_BfcCsFHQiQpVDVHT7qU/view?usp=sharing)
[4 - What They Don't Know Can Hurt Them: Mothers' Legal Knowledge and Youth Re-Offending by Cavanagh Cauffman](https://drive.google.com/file/d/1jyolI0IQXeYYRtPgqhs7VN8AZYDpeSIN/view?usp=sharing)
[5 - Community Support Checklist](https://drive.google.com/file/d/1eVaABK8Dd0Xa9HrQ0s0QgpdWjo6zVUeL/view?usp=sharing)
[6 - Final Dependency Presentation](https://drive.google.com/file/d/1nS__d1_wa6UwIPZiCWUkmPnUoeFrxdQP/view?usp=sharing)
[7 - Questions to Ask Your Attorney](https://drive.google.com/file/d/1Lm1b73Ox3JXgHSG7uqd0aoVoBTaW_HYc/view?usp=sharing)

**Comment by ExperimentsInHonesty** [comment]
9 - [Juveniles Beliefs](https://drive.google.com/file/d/1pnIjip3ftANSEWcv0-DVZbOOvNiuVC-V/view?usp=sharing)

**Comment by Rankazze** [comment]
After reading the Juveniles Beliefs research paper I suspect that this reference will be good to dive into for our JPO Persona Mind Mapping research.
Desktop Guide to Good Juvenile
Probation Practice (Griffin & Torbet, 2002; Hsieh et al., 2016).

**Comment by Rankazze** [comment]
After reading #8 above I also benefited from this NNG research [Teenager’s UX: Designing for Teens](https://www.nngroup.com/articles/usability-of-websites-for-teenagers/)

**Comment by Olivia-Chiong** [comment]
I think this section in the teenagers guide above is crucial in our product design decision 

Teens perform worse than adults for three reasons:

Insufficient reading skills
Less sophisticated research strategies
Dramatically lower levels of patience
To improve your site’s usability among teens, you must consider all three factors. Also note that we have seen these factors in all our research with teenagers during a 15-year period, meaning that they are likely to continue to hold in the future, even if other teen habits may change as fads come and go.

Across different types of websites, teens had the most success on ecommerce websites, which often adhered to design standards and required little reading. Teens encountered the greatest challenges on large sites with dense content and poor navigation schemes. Government, nonprofit, and school sites were the biggest culprits of poor usability.

**Comment by Olivia-Chiong** [comment]
12. [Notes from community brainstorming](https://drive.google.com/file/d/1gr5j-KKAJG76cXV0Ifl3MRzii2Rqk5UC/view?usp=sharing)
13. [Original Juvenile Justice Manual](https://drive.google.com/file/d/187_bQXhWuXZ4dNv3cKCr4XmwvAEPyhOZ/view?usp=sharing)
14. [Word document for Court process for Juveniles](https://drive.google.com/file/d/151FijrxoBO791CF_heYx5N8UNzdHf_Kr/view?usp=sharing)
15. [Juvenile Justice Manual annotated by Alicia and Jyoti](https://drive.google.com/file/d/1mH0VMtK3OZZnFoUzH8LeElR4oKCf26s7/view?usp=sharing)
16. [Knowledge is Power Style Guide](https://drive.google.com/file/d/1yFOojNO2WYNL1sVqumkalGpD5NZXWFBQ/view?usp=sharing)

**Comment by reeree1022** [comment]
My  review of the documents in the Drive.

Root folder has my comments in the following doc files:

- YJN Initial Personas [INTERNAL] 
- YJN: Customer Discovery Step by Step

(Note that the YJN Initial Issues sheet has a copy without any changes in it. This is a candidate for a new templates folder when you re-organize the Drive.)

Materials from UCLA & GGU folder has my comments in the following doc files:
2-Knowledge is Power Content Map-10.2020 (4)

4-Cavanagh doc version is not readable the way it is formatted.  It's in 6 pt font and I had to look at PDF to follow the content. Even then, it's super technical and I didn't understand half of it.

8 JuvenilesBeliefs - I understood the beginning, but most is over my head (legalese).

JJ Manual LAC - Is any of this already incorporated in the manual (pdf number 13)?

Communications Guide >  YJN Communications Guide for Document Creation [INTERNAL]:I was confused about what this was until I paged through it. So I suggest changing the tile and page 1 to either "Communications Style Guide" or "YJN Style Guide" for simplicity.  (couldn't add comments in Drive) 

For the annotated version of the manual (PDF 15), is there a separate document where they have explained the content marked as Change (i.e., what should be changed)?

> 
> 
>     1. [Notes from community brainstorming](https://drive.google.com/file/d/1gr5j-KKAJG76cXV0Ifl3MRzii2Rqk5UC/view?usp=sharing)
> 
>     2. [Original Juvenile Justice Manual](https://drive.google.com/file/d/187_bQXhWuXZ4dNv3cKCr4XmwvAEPyhOZ/view?usp=sharing)
> 
>     3. [Word document for Court process for Juveniles](https://drive.google.com/file/d/151FijrxoBO791CF_heYx5N8UNzdHf_Kr/view?usp=sharing)
> 
>     4. [Juvenile Justice Manual annotated by Alicia and Jyoti](https://drive.google.com/file/d/1mH0VMtK3OZZnFoUzH8LeElR4oKCf26s7/view?usp=sharing)
> 
>     5. [Knowledge is Power Style Guide](https://drive.google.com/file/d/1yFOojNO2WYNL1sVqumkalGpD5NZXWFBQ/view?usp=sharing)

**Comment by reeree1022** [comment]
While meeting with the team today, I re-organized the files in the Materials folder and the root folder, including what I mentioned in my comment above.  I changed all folder permissions I created so everyone can access them, and they have retained their links.  

As new files are created, say in Information Dump folder, we should continue categorizing the info so all teams members (new like me or not) can more easily find these resources. If you have trouble finding anything, you can also click on the links that Leroy and Bonnie have given above to get back to them.
