### ISSUE TITLE
Setup Facebook account for YouthJusticeNav

### ISSUE THREAD

**Issue by nielseny** [hackforla/YouthJusticeNav#4]
### Overview
Create a Facebook account for YouthJusticeNav and add the link to the project board so we don't lose it. 

### Action Items

- [x] Setup Facebook account
- [ ] Add Facebook password to 1password
- [x] Add link to Facebook account on project board

### Resources/Instructions
[Location to paste links on board ](https://github.com/hackforla/YouthJusticeNav/projects/1#card-51795877)

**Comment by ltung05** [comment]
https://www.facebook.com/youthjusticenav
