### ISSUE TITLE
Get connected with Liberty Hill to figure out administrative procedures

### ISSUE THREAD

**Issue by Olivia-Chiong** [hackforla/YouthJusticeNav#40]
### Overview
We need to get connected with Liberty Hill and sign the contract so we can proceed with the project.

### Action Items
- [x] Follow up with Lisa Small on what is required after Alicia has spoken to her
- [x] Prepare documentation for submission
   - [x] [Roles and responsibilities document](https://docs.google.com/document/d/1gMXhs0AE8nQasI9cNFYGTxhb8A-GOGnYqpjuJScbhvc/edit?usp=sharing)

### Resources/Instructions
[Role descriptions](https://github.com/hackforla/civic-opportunity/tree/master/roles-1)

**Comment by Olivia-Chiong** [comment]
Lisa has replied and we are gathering the documentation to send to her. ETA end of next week - 3/5/2021

**Comment by ltung05** [comment]
The email needs to be sent to Liberty Hill @ExperimentsInHonesty

**Comment by Olivia-Chiong** [comment]
Pending non-profit status from IRS
