### ISSUE TITLE
Research websites that are interesting to young people

### ISSUE THREAD

**Issue by Olivia-Chiong** [hackforla/YouthJusticeNav#49]
### Overview
We need to research website layouts/formats that are interesting to young people and have high engagement with the youth audience

### Action Items
- [x] Make a list of websites
- [ ] Compare the features/designs
- [ ] Come up with our list of features/designs we want

### Resources/Instructions
[List of interesting websites](https://docs.google.com/document/d/1jpiCHnBmUg91FnnlwikQIQK1cNLMmBvMUZkUpwS8o6s/edit)

**Comment by chalimar** [comment]
Interviews have been [conducted](https://docs.google.com/document/d/1wFlHRIs-a-8iCby6pl7wPxQH0OcMViH5eIKXcRrO0lY/edit) and [synthesized.](https://docs.google.com/presentation/d/1EWHb1QGROCda9NQTLelJvYnU9ooXNYtWvYflSTP-2FM/edit#slide=id.p)
