### ISSUE TITLE
Setup Instagram account for YouthJusticeNav

### ISSUE THREAD

**Issue by nielseny** [hackforla/YouthJusticeNav#5]
### Overview
Create an Instagram account for YouthJusticeNav and add the link to the project board so we don't lose it. 

### Action Items

- [x] Setup Instagram account
- [x] Add Instagram password to 1password
- [x] Add link to Instagram account on project board

### Resources/Instructions
[Location to paste links on board ](https://github.com/hackforla/YouthJusticeNav/projects/1#card-51795877)

**Comment by j100892** [comment]
We already have an Instagram account that was created by Leroy.

**Comment by nielseny** [comment]
Thanks Daniel. @ltung05, if you have created an Instagram account for YouthJusticeNav, can you add the login details to 1Password, please? Thanks!

**Comment by ltung05** [comment]
@nielseny I'm responsible for the Facebook page. I will work on that tonight, can't change admin settings for some reason, will figure that part out.
