### ISSUE TITLE
New Name for YJN

### ISSUE THREAD

**Issue by Olivia-Chiong** [hackforla/YouthJusticeNav#50]
### Overview
We need to brainstorm a new name for YJN

### Action Items
- [x] Brainstorm with Jyoti's students
- [x] Brainstorm with team
- [x] Brainstorm with advisory board
- [x] Check domain name availability
- [x] Final name list selection

### Resources/Instructions
[Miro Board with Names](https://miro.com/app/board/o9J_lVDrmlY=/)

**Comment by chalimar** [comment]
Finalized project name is **Youth Justice Navigator** and will be accessible at youthjusticenavigator.org and at youthjusticenavigator.com.
