### ISSUE TITLE
Create a flyer to recruit interviewees

### ISSUE THREAD

**Issue by Olivia-Chiong** [hackforla/YouthJusticeNav#53]
### Overview
We need to create a flyer so it can be used to recruit interviewees.

### Action Items
- [ ] Draft text to be included in flyer
- [ ] Create flyer
- [ ] Review with the team

### Resources/Instructions
[Information for flyer](https://docs.google.com/document/d/1Wn-FPAV2VAS1fOi9Q_3juQBVSegUyNzlywzFTUItqF8/edit)

**Comment by chalimar** [comment]
Attaching latest version of flyer [here.](https://www.canva.com/design/DAEi-wuQ--I/LLwsWPoRl2Y6GwnuCUBgZg/view)
