### ISSUE TITLE
Update Github Project Description and License 

### ISSUE THREAD

**Issue by j100892** [hackforla/YouthJusticeNav#7]
### Overview
We need to update our project descriptions with new copy that replaces the current placeholder copy and add a license to the things that we are building.

### Action Items
- [ ] Update Project Description and other items within that page with relevant info/contacts 
- [x] Add MIT license or other open source license on that same page under "licensing" 

### Resources/Instructions
[Location of fields to edit ](https://github.com/hackforla/YouthJusticeNav)

**Comment by nielseny** [comment]
I've added the license and some basic information. https://github.com/hackforla/YouthJusticeNav/blob/main/README.md

Will add more information as we have more collateral to add (project one pager, onboarding doc, etc)

**Comment by ltung05** [comment]
For reference, steps to join the team:
https://github.com/hackforla/website/wiki/Joining-the-HackforLA.org-website-team
