### ISSUE TITLE
Analyze SDG Goal for Youth Justice Nav

### ISSUE THREAD

**Issue by ltung05** [hackforla/YouthJusticeNav#8]
### Overview
We need to identify the accurate SDG goal under goal 16 so this project can appear when people search for SDG.

### Action Items
Research and analyze under LA SDG identify the exact segment with goal 16.

### Resources/Instructions
https://sdgdata.lamayor.org/16/

**Comment by nielseny** [comment]
Could be relevant to the following: 

- 16.3: Promote the rule of law at the City level and ensure equal access to justice for all
- 16.6: Develop effective, accountable and transparent institutions at all levels
- 16.7: Ensure responsive, inclusive, participatory and representative decision-making at all levels

**Comment by Olivia-Chiong** [comment]
@nielseny and @ltung05 did you ever decide which one was best?

**Comment by ltung05** [comment]
This has been confirmed to:

- Ensure equal opportunity and reduce inequalities of outcome, including by eliminating discriminatory laws, policies and practices and promoting appropriate legislation, policies and action in this regard
